trigger:
- master
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: azure-acr-connection

steps:
- task: Docker@2
  displayName: Build and push a frontend image to container registry
  inputs:
    command: buildAndPush
    repository: azure-devops-sample
    containerRegistry: $(dockerRegistryServiceConnection)
    Dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)
      latest

